name = "DataWorkstation"
uuid = "e0ebcb34-69ae-4d20-9e42-b33a0f43aa89"
authors = ["Leandro Ferrado <leferrad@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
julia = "1.6.5"

[extras]
JuliaFormatter = "98e50ef6-434e-11e9-1051-2b60c6c9e899"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
